# Generated by Django 2.1 on 2018-08-15 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0003_system_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='system',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='status',
            field=models.CharField(choices=[('READY', 'READY'), ('TRAINING', 'TRAINING'), ('ERROR', 'ERROR')], default='READY', max_length=8),
        ),
    ]
