# Generated by Django 2.1 on 2018-08-15 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0008_dataset_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surrogate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='system',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('READY', 'READY'), ('TRAINING', 'TRAINING'), ('ERROR', 'ERROR')], default='CREATED', max_length=8),
        ),
        migrations.AddField(
            model_name='surrogate',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surrogate', to='modeling.System'),
        ),
    ]
