# Generated by Django 2.1 on 2018-08-17 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0009_auto_20180815_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputvariable',
            name='lower_bound',
        ),
        migrations.RemoveField(
            model_name='inputvariable',
            name='upper_bound',
        ),
    ]
