# Generated by Django 2.1 on 2018-08-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0010_auto_20180817_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='surrogate',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surrogate',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
