# Generated by Django 2.1 on 2018-09-01 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0011_auto_20180823_2230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Surrogate',
            new_name='SurrogateModel',
        ),
    ]
