# Generated by Django 2.1 on 2018-09-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0012_auto_20180901_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('READY', 'READY'), ('BUSY', 'BUSY'), ('ERROR', 'ERROR')], default='CREATED', max_length=8),
        ),
    ]
